In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)
print("Jupyter is working!")

Pandas version: 3.0.6
Jupyter is working!

In [2]:
orders = {
    "order_id": [101, 102, 103, 104, 105, 106],
    "customer": ["Aman", "Priya", "Rahul", "Neha", "Aman", "Kavya"],
    "product": ["Keyboard", "Mouse", "Monitor", "Mouse", "Laptop", "Headphones"],
    "quantity": [1, 2, 1, 3, 1, 2],
    "price": [1500, 500, 12000, 500, 55000, 2500]
}

df = pd.DataFrame(orders)
df

   order_id customer     product  quantity  price
0       101     Aman    Keyboard         1   1500
1       102    Priya       Mouse         2    500
2       103    Rahul     Monitor         1  12000
3       104     Neha       Mouse         3    500
4       105     Aman      Laptop         1  55000
5       106    Kavya  Headphones         2   2500

In [3]:
# Save the DataFrame as a CSV file
df.to_csv("orders.csv", index=False)

print("CSV file saved successfully!")

CSV file saved successfully!

In [4]:
# Read the saved CSV file
df_csv = pd.read_csv("orders.csv")

# Display the first five rows
df_csv.head()

   order_id customer   product  quantity  price
0       101     Aman  Keyboard         1   1500
1       102    Priya     Mouse         2    500
2       103    Rahul   Monitor         1  12000
3       104     Neha     Mouse         3    500
4       105     Aman    Laptop         1  55000

In [5]:
print("Rows:", len(df_csv))
print("Columns:", len(df_csv.columns))
print("Missing values:\n", df_csv.isnull().sum())

Rows: 6
Columns: 5
Missing values:
 order_id    0
customer    0
product     0
quantity    0
price       0
dtype: int64

In [6]:
import json

order = {
    "order_id": 101,
    "customer": "Aman",
    "product": "Keyboard",
    "quantity": 1,
    "price": 1500
}

# Write Python data to a JSON file
with open("order.json", "w") as file:
    json.dump(order, file, indent=4)

print("JSON file created!")

JSON file created!

In [7]:
# Read the JSON file
with open("order.json", "r") as file:
    loaded_order = json.load(file)

print(loaded_order)
print("Customer:", loaded_order["customer"])
print("Order total:", loaded_order["quantity"] * loaded_order["price"])

{'order_id': 101, 'customer': 'Aman', 'product': 'Keyboard', 'quantity': 1, 'price': 1500}
Customer: Aman
Order total: 1500

In [8]:

import json

order = {
    "order_id": 201,
    "customer": {
        "name": "Aman",
        "city": "Delhi"
    },
    "items": [
        {"product": "Keyboard", "quantity": 1, "price": 1500},
        {"product": "Mouse", "quantity": 2, "price": 500}
    ],
    "status": "Delivered"
}

# Save the nested dictionary as JSON
with open("nested_order.json", "w") as file:
    json.dump(order, file, indent=4)

# Read the JSON file
with open("nested_order.json", "r") as file:
    data = json.load(file)

print("Customer:", data["customer"]["name"])
print("City:", data["customer"]["city"])
print("First product:", data["items"][0]["product"])
print("Order status:", data["status"])

Customer: Aman
City: Delhi
First product: Keyboard
Order status: Delivered

In [9]:
total = sum(item["quantity"] * item["price"] for item in data["items"])
print("Order total:", total)

Order total: 2500

In [10]:
import pandas as pd

# Convert nested JSON object into a flat table
df_order = pd.json_normalize(order)

df_order

,order_id,items,status,customer.name,customer.city
0,201,"[{'product': 'Keyboard', 'quantity': 1, 'price...",Delivered,Aman,Delhi

In [11]:
df_items = pd.json_normalize(
    order,
    record_path="items",
    meta=["order_id", ["customer", "name"], ["customer", "city"], "status"]
)

df_items

    product  quantity  price order_id customer.name customer.city     status
0  Keyboard         1   1500      201          Aman         Delhi  Delivered
1     Mouse         2    500      201          Aman         Delhi  Delivered

In [12]:
{"product": "Monitor", "quantity": 1, "price": 12000}

{'product': 'Monitor', 'quantity': 1, 'price': 12000}

In [13]:

import json
import pandas as pd

# Simulated API response
api_response = {
    "success": True,
    "orders": [
        {
            "order_id": 301,
            "customer": {"name": "Aman", "city": "Delhi"},
            "amount": 2000,
            "status": "Delivered"
        },
        {
            "order_id": 302,
            "customer": {"name": "Priya", "city": "Mumbai"},
            "amount": 3500,
            "status": "Shipped"
        },
        {
            "order_id": 303,
            "customer": {"name": "Rahul", "city": "Pune"},
            "amount": 1500,
            "status": "Pending"
        }
    ]
}

print("API success:", api_response["success"])
print("Number of orders:", len(api_response["orders"]))

API success: True
Number of orders: 3

In [14]:

df_api = pd.json_normalize(api_response["orders"])

df_api

   order_id  amount     status customer.name customer.city
0       301    2000  Delivered          Aman         Delhi
1       302    3500    Shipped         Priya        Mumbai
2       303    1500    Pending         Rahul          Pune

In [15]:

print("Rows:", len(df_api))
print("\nMissing values:")
print(df_api.isnull().sum())

print("\nTotal order value:", df_api["amount"].sum())
print("Average order value:", df_api["amount"].mean())

Rows: 3

Missing values:
order_id         0
amount           0
status           0
customer.name    0
customer.city    0
dtype: int64

Total order value: 7000
Average order value: 2333.3333333333335

In [16]:
print("\nOrders by status:")
print(df_api["status"].value_counts())

Orders by status:
status
Delivered    1
Shipped      1
Pending      1
Name: count, dtype: int64

In [17]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\Users\pc\anaconda3\Lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import pandas as pd
import pyarrow as pa

print("Pandas:", pd.__version__)
print("PyArrow:", pa.__version__)
print("Parquet setup successful!")

Pandas: 3.0.6
PyArrow: 23.0.1
Parquet setup successful!

In [19]:

import pandas as pd
import numpy as np

# Make results reproducible
np.random.seed(42)

n = 10_000

df = pd.DataFrame({
    "order_id": range(10001, 10001 + n),
    "customer_id": np.random.randint(1000, 3000, n),
    "product": np.random.choice(
        ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones"],
        n
    ),
    "quantity": np.random.randint(1, 6, n),
    "unit_price": np.random.choice(
        [500, 1000, 1500, 5000, 25000, 55000],
        n
    ),
    "city": np.random.choice(
        ["Delhi", "Mumbai", "Pune", "Bengaluru", "Chennai"],
        n
    ),
    "status": np.random.choice(
        ["Delivered", "Shipped", "Pending", "Cancelled"],
        n
    )
})

df["total_amount"] = df["quantity"] * df["unit_price"]

print("Dataset created!")
print("Shape:", df.shape)
display(df.head())

Dataset created!
Shape: (10000, 8)

,order_id,customer_id,product,quantity,unit_price,city,status,total_amount
0,10001,2126,Headphones,2,5000,Delhi,Delivered,10000
1,10002,2459,Keyboard,2,1000,Mumbai,Cancelled,2000
2,10003,1860,Mouse,5,1500,Chennai,Delivered,7500
3,10004,2294,Keyboard,1,500,Pune,Cancelled,500
4,10005,2130,Laptop,4,1500,Mumbai,Shipped,6000

In [20]:
df.to_csv("orders.csv", index=False)

print("CSV saved successfully!")

CSV saved successfully!

In [21]:
df.to_json("orders.json", orient="records", indent=2)

print("JSON saved successfully!")

JSON saved successfully!

In [22]:
df.to_parquet("orders.parquet", index=False, engine="pyarrow")

print("Parquet saved successfully!")

Parquet saved successfully!

In [23]:
from pathlib import Path

for filename in ["orders.csv", "orders.json", "orders.parquet"]:
    path = Path(filename)
    print(filename, "exists:", path.exists())

orders.csv exists: True
orders.json exists: True
orders.parquet exists: True

In [24]:
# Read the Parquet file
df_parquet = pd.read_parquet(
    "orders.parquet",
    engine="pyarrow"
)

# Display the first 5 rows
df_parquet.head()

,order_id,customer_id,product,quantity,unit_price,city,status,total_amount
0,10001,2126,Headphones,2,5000,Delhi,Delivered,10000
1,10002,2459,Keyboard,2,1000,Mumbai,Cancelled,2000
2,10003,1860,Mouse,5,1500,Chennai,Delivered,7500
3,10004,2294,Keyboard,1,500,Pune,Cancelled,500
4,10005,2130,Laptop,4,1500,Mumbai,Shipped,6000

In [25]:
print("Rows:", len(df_parquet))
print("Columns:", len(df_parquet.columns))
print("Data types:")
print(df_parquet.dtypes)

Rows: 10000
Columns: 8
Data types:
order_id        int64
customer_id     int32
product           str
quantity        int32
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

In [26]:
from pathlib import Path
import pandas as pd

files = ["orders.csv", "orders.json", "orders.parquet"]

for filename in files:
    size_bytes = Path(filename).stat().st_size
    size_kb = size_bytes / 1024

    print(f"{filename}: {size_kb:.2f} KB")

orders.csv: 480.97 KB
orders.json: 1877.39 KB
orders.parquet: 105.98 KB

In [27]:
size_data = []

for filename in files:
    size_bytes = Path(filename).stat().st_size

    size_data.append({
        "format": filename.split(".")[-1].upper(),
        "size_bytes": size_bytes,
        "size_kb": round(size_bytes / 1024, 2)
    })

size_df = pd.DataFrame(size_data)
size_df

    format  size_bytes  size_kb
0      CSV      492517   480.97
1     JSON     1922444  1877.39
2  PARQUET      108521   105.98

In [28]:
df_csv = pd.read_csv("orders.csv")
df_json = pd.read_json("orders.json", orient="records")
df_parquet = pd.read_parquet("orders.parquet")

print("CSV matches original:", df.equals(df_csv))
print("JSON matches original:", df.equals(df_json))
print("Parquet matches original:", df.equals(df_parquet))

CSV matches original: False
JSON matches original: False
Parquet matches original: True

In [30]:

from pathlib import Path
import pandas as pd

# Load all three formats
loaded_data = {
    "CSV": pd.read_csv("orders.csv"),
    "JSON": pd.read_json("orders.json", orient="records"),
    "Parquet": pd.read_parquet("orders.parquet", engine="pyarrow")
}

# Compare file sizes and data consistency
results = []

for format_name, loaded_df in loaded_data.items():
    extension = format_name.lower()
    file_path = Path(f"orders.{extension}")

    results.append({
        "Format": format_name,
        "Rows": len(loaded_df),
        "Columns": len(loaded_df.columns),
        "Size (KB)": round(file_path.stat().st_size / 1024, 2),
        "Matches Original": df.equals(loaded_df)
    })

report = pd.DataFrame(results)
display(report)

# Verify all formats contain the expected data
assert len(df) == 10_000, "Unexpected original row count!"

for format_name, loaded_df in loaded_data.items():
    assert df.equals(loaded_df), f"{format_name} data mismatch!"

print("SUCCESS: All formats match the original dataset.")

    Format   Rows  Columns  Size (KB)  Matches Original
0      CSV  10000        8     480.97             False
1     JSON  10000        8    1877.39             False
2  Parquet  10000        8     105.98              True

AssertionError: CSV data mismatch!

In [31]:
print("Original data types:")
print(df.dtypes)

print("\nCSV data types:")
print(df_csv.dtypes)

Original data types:
order_id        int64
customer_id     int32
product           str
quantity        int32
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

CSV data types:
order_id        int64
customer_id     int64
product           str
quantity        int64
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

In [32]:
print("Original shape:", df.shape)
print("CSV shape:", df_csv.shape)

print("\nColumns in original:", df.columns.tolist())
print("Columns in CSV:", df_csv.columns.tolist())

Original shape: (10000, 8)
CSV shape: (10000, 8)

Columns in original: ['order_id', 'customer_id', 'product', 'quantity', 'unit_price', 'city', 'status', 'total_amount']
Columns in CSV: ['order_id', 'customer_id', 'product', 'quantity', 'unit_price', 'city', 'status', 'total_amount']

In [33]:
print("Original shape:", df.shape)
print("CSV shape:", loaded_data["CSV"].shape)

print("\nOriginal columns:")
print(df.columns.tolist())

print("\nCSV columns:")
print(loaded_data["CSV"].columns.tolist())

print("\nData types equal:",
      df.dtypes.equals(loaded_data["CSV"].dtypes))

print("\nFirst differing rows (if any):")
print(df.compare(loaded_data["CSV"]) if df.shape == loaded_data["CSV"].shape
      and df.columns.equals(loaded_data["CSV"].columns)
      else "Shape or columns differ")

Original shape: (10000, 8)
CSV shape: (10000, 8)

Original columns:
['order_id', 'customer_id', 'product', 'quantity', 'unit_price', 'city', 'status', 'total_amount']

CSV columns:
['order_id', 'customer_id', 'product', 'quantity', 'unit_price', 'city', 'status', 'total_amount']

Data types equal: False

First differing rows (if any):
Empty DataFrame
Columns: []
Index: []

In [34]:
df.to_csv("orders.csv", index=False)
df.to_json("orders.json", orient="records", indent=2)
df.to_parquet("orders.parquet", index=False, engine="pyarrow")

In [35]:
df_csv = pd.read_csv("orders.csv")
df_json = pd.read_json("orders.json", orient="records")
df_parquet = pd.read_parquet("orders.parquet")

In [36]:
print("CSV:", df.equals(df_csv))
print("JSON:", df.equals(df_json))
print("Parquet:", df.equals(df_parquet))

CSV: False
JSON: False
Parquet: True

In [37]:
print("ORIGINAL DATA TYPES")
print(df.dtypes)

print("\nCSV DATA TYPES")
print(df_csv.dtypes)

print("\nJSON DATA TYPES")
print(df_json.dtypes)

ORIGINAL DATA TYPES
order_id        int64
customer_id     int32
product           str
quantity        int32
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

CSV DATA TYPES
order_id        int64
customer_id     int64
product           str
quantity        int64
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

JSON DATA TYPES
order_id        int64
customer_id     int64
product           str
quantity        int64
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

In [39]:
for name, loaded in [
    ("CSV", df_csv),
    ("JSON", df_json),
    ("Parquet", df_parquet)
]:
    print(f"\n{name}")
    print("Same shape:", df.shape == loaded.shape)
    print("Same columns:", df.columns.equals(loaded.columns))
    print("Same data types:", df.dtypes.equals(loaded.dtypes))

CSV
Same shape: True
Same columns: True
Same data types: False

JSON
Same shape: True
Same columns: True
Same data types: False

Parquet
Same shape: True
Same columns: True
Same data types: True

In [40]:
print("ORIGINAL DATA TYPES")
print(df.dtypes)

print("\nCSV DATA TYPES")
print(df_csv.dtypes)

print("\nJSON DATA TYPES")
print(df_json.dtypes)

ORIGINAL DATA TYPES
order_id        int64
customer_id     int32
product           str
quantity        int32
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

CSV DATA TYPES
order_id        int64
customer_id     int64
product           str
quantity        int64
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

JSON DATA TYPES
order_id        int64
customer_id     int64
product           str
quantity        int64
unit_price      int64
city              str
status            str
total_amount    int64
dtype: object

In [41]:
print("CSV Mismatches:")
for col in df.columns:
    if df[col].dtype != df_csv[col].dtype:
        print(col, "| Original:", df[col].dtype, "| CSV:", df_csv[col].dtype)

print("\nJSON Mismatches:")
for col in df.columns:
    if df[col].dtype != df_json[col].dtype:
        print(col, "| Original:", df[col].dtype, "| JSON:", df_json[col].dtype)

CSV Mismatches:
customer_id | Original: int32 | CSV: int64
quantity | Original: int32 | CSV: int64

JSON Mismatches:
customer_id | Original: int32 | JSON: int64
quantity | Original: int32 | JSON: int64

In [42]:
# Convert mismatched columns to original data types
for col in df.columns:
    df_csv[col] = df_csv[col].astype(df[col].dtype)
    df_json[col] = df_json[col].astype(df[col].dtype)

print("CSV matches:", df.equals(df_csv))
print("JSON matches:", df.equals(df_json))
print("Parquet matches:", df.equals(df_parquet))

CSV matches: True
JSON matches: True
Parquet matches: True

In [43]:
from pathlib import Path

files = ["orders.csv", "orders.json", "orders.parquet"]

for file in files:
    size_kb = Path(file).stat().st_size / 1024
    print(f"{file}: {size_kb:.2f} KB")

orders.csv: 480.97 KB
orders.json: 1877.39 KB
orders.parquet: 105.98 KB

In [44]:
csv_size = Path("orders.csv").stat().st_size
json_size = Path("orders.json").stat().st_size
parquet_size = Path("orders.parquet").stat().st_size

print(f"Parquet vs CSV: {parquet_size / csv_size:.2%}")
print(f"Parquet vs JSON: {parquet_size / json_size:.2%}")

Parquet vs CSV: 22.03%
Parquet vs JSON: 5.64%